# Generated by Django 2.2.4 on 2022-01-17 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('his_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image_input', models.ImageField(default='', null=True, upload_to='media/images_as_input')),
                ('image_output', models.ImageField(blank=True, default='', null=True, upload_to='media/images_as_output')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 17, 15, 43, 32, 44022))),
            ],
        ),
        migrations.CreateModel(
            name='NumberPlateHistory',
            fields=[
                ('num_his_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_name', models.CharField(max_length=100)),
                ('num_image_input', models.ImageField(default='', null=True, upload_to='media/image_input_number_plate')),
                ('num_image_output', models.ImageField(blank=True, default='', null=True, upload_to='media/image_output_number_plate')),
                ('num_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 17, 15, 43, 32, 44876))),
            ],
        ),
    ]
