# Generated by Django 2.2.4 on 2022-01-17 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 17, 17, 43, 52, 688566)),
        ),
        migrations.AlterField(
            model_name='numberplatehistory',
            name='num_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 17, 17, 43, 52, 688950)),
        ),
    ]
